#!/bin/sh

if [ $# -ne 3 ]; then
	echo "Wrong shebang: #!/usr/bin/env dk IMAGE ENTRYPOINT"
	exit 1
else
	docker run \
		--rm \
		--volume="$(PWD):/opt" \
		--workdir="/opt" \
		--env "HOST_CWD=$(PWD)" \
		-it \
		--entrypoint "" \
		"$1" "$2" "$3"
fi
