#!/bin/sh -e
#
# doi2bib - downloads bibtex citation from a DOI provider
# requires curl

curl -Ls -H "Accept: application/x-bibtex" "$1" # or
# curl -s "http://api.crossref.org/works/$1/transform/application/x-bibtex" -w "\\n"
