#!/bin/sh -e
#
# doi2pdf - downloads papers from sci-hub based on DOI number

die() {
	echo "$1" 1>&2
	exit 1
}

SCIHUB_URL="https://sci-hub.st/"
DOI="$1"
PDF_URL=$(curl -Ls "${SCIHUB_URL}/${DOI}" |
	hxnormalize -x |
	hxselect -i -c "iframe::attr(src)"
)

key="$(curl -Ls -H "Accept: application/x-bibtex" "doi.org/$1" |
	head -n +1 | cut -d'{' -f2 | tr '[:upper:]' '[:lower:]' | tr -d '_,'
)"

curl -Ls "$PDF_URL" -o "${key}.pdf" || die "download failed."
echo "${key}.pdf"
