#!/bin/sh -e
#
# doi2bib - downloads bibtex citation from a DOI provider, given DOI URL

bib="$(curl -Ls -H "Accept: application/x-bibtex" "doi.org/$1")"

echo "$bib" | head -n +1 | tr '[:upper:]' '[:lower:]' | tr -d '_'
echo "$bib" | tail -n +2
