#!/bin/sh -e
#
# git-get -- "go get" for all git repos

die() {
	printf "%s: %s\n" "$0" "$@"
	exit 1
}

GIT_PATH="$HOME/src"

case "$1" in
	git://*) repo=${1#git://*}; ;;
	ssh://*) repo=${1#ssh://*@}; ;;
	https://*) repo=${1#https://*}; ;;
	*/*) die "incorrect url"; ;;
esac

repo=${repo%*.git}
path="$GIT_PATH/$repo"

[ -z "$path" ] && die "failed to get repository path"
[ -e "$path" ] && die "repository already exists"

mkdir -p "$(dirname "$path")" &&
(
	git clone --depth=1 -o upstream "$1" "$path" ||
	rm -r "$path"
)
