#!/bin/sh -e
#
# git-get - a minimal copy of "go get"

_err() {
	printf "%s: %s\n" "$0" "$@"
	exit 1
}

GIT_PATH="$HOME/src"

case "$1" in
	git://*) repo=${1#git://*}; ;;
	ssh://*) repo=${1#ssh://*@}; ;;
	https://*) repo=${1#https://*}; ;;
	*/*) _err 'incorrect url'; ;;
esac

repo=${repo%*.git}
path="$GIT_PATH/$repo"

[ -z "$path" ] && _err 'failed to get repository path'
[ -e "$path" ] && _err 'repository already exists'

mkdir -p "$(dirname "$path")" &&
(
	git clone --depth=1 -o upstream "$1" "$path" ||
	rm -r "$path"
)
