#!/bin/sh -e
#
# mproc: process mail

reindex() {
	if command -v mu >/dev/null; then mu index --quiet; fi
	if command -v notmuch >/dev/null; then notmuch new --quiet; fi
}

process() {
	mlist "$1/INBOX" | mpick -t "$2" | mrefile "$1/$3"
}

reindex
