#!/bin/sh -e
[ ! -t 0 ] && eq=$(cat); eq="${eq:-$1}"

tmpdir="/tmp/tex2svg_cache"
mkdir -p "${tmpdir}"
eqhash=$(md5 -q -s "${eq}")
texfile="${tmpdir}/${eqhash}.tex"
dvifile="${tmpdir}/${eqhash}.dvi"
svgfile="${tmpdir}/${eqhash}.svg"

if [ -z "$eq" ]; then
	cat <<EOF
usage:
	tex2svg "a+b=c"
	echo "a+b=c" | tex2svg
EOF
	exit 1
fi

if [ ! -f "${svgfile}" ]; then
	if [ ! -f "${dvifile}" ]; then
		if [ ! -f "${texfile}" ]; then
			cat <<EOF > "${texfile}"
\\documentclass[border=1pt,varwidth]{standalone}
\\usepackage{standalone}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{cancel}
\\begin{document}
\\(${eq}\\)
\\end{document}
EOF
		fi
		latex -output-directory="${tmpdir}" "${texfile}" > /dev/null 2>&1 || exit 1
	fi
	dvisvgm -v 0 -b2pt -Z1.2 -n -o "${svgfile}" "${dvifile}" > /dev/null 2>&1 || exit 1
fi
cat "${svgfile}"

exit 0
