#!/bin/sh -e
[ ! -t 0 ] && eq=$(cat); eq="${eq:-$1}"

tmpdir="$(mktemp -d)"
mkdir -p "$tmpdir"
trap 'rm -r "$tmpdir"' EXIT

texfile="${tmpdir}/0.tex"
dvifile="${tmpdir}/0.dvi"
svgfile="${tmpdir}/0.svg"

if [ -z "$eq" ]
then
	cat <<EOF
usage:
	tex2svg "a+b=c"
	echo "a+b=c" | tex2svg
EOF
	exit 1
fi

cat <<EOF > "${texfile}"
\\documentclass[border=1pt,varwidth]{standalone}
\\usepackage{standalone}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{cancel}
\\begin{document}
\\(${eq}\\)
\\end{document}
EOF

latex -output-directory="${tmpdir}" "${texfile}" > /dev/null 2>&1 || exit 1
dvisvgm -v 0 -b2pt -Z1.2 -n -o "${svgfile}" "${dvifile}" > /dev/null 2>&1 || exit 1
cat "${svgfile}"

exit 0
